using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _737Connector
{
    class Board
    {
        enum Pins 
        {
            PC7_2=1,
            PA0_2,
            PB5_2,
            PB4_2,
            PB3_2,
            PB2_2,
            PB1_2,
            PB0_2,
            PD7_2,
            PD5_2,
            PB6_2,
            PA3_2,
            PD4_2,
            PD3_2,
            PC7_1,
            PA0_1,
            PA2_2,
            PB7_2,
            PD6_2,
            PB5_1,
            PB4_1,
            PB3_1,
            PB2_1,
            PB1_1,
            PB0_1,
            PD7_1,
            PD6_1,
            PD5_1,
            PB7_1,
            PB6_1,
            PA3_1,
            PA2_1,
            PD4_1,
            PD3_1,
            PD2_1,
            PD1_1,
            PD0_1,
            PC3_1,
            PC2_1,
            PC1_1,
            PC0_1,
            PA1_1,
            PD2_2,
            PD1_2,
            PD0_2,
            PC3_2,
            PC2_2,
            PC1_2,
            PC0_2,
            PA1_2,
            PA2_3,
            PD4_3,
            PD3_3,
            PD2_3,
            PD1_3,
            PD0_3,
            PC3_3,
            PC2_3,
            PD2_4,
            PD1_4,
            PD0_4,
            PC3_4,
            PC2_4,
            PC1_4,
            PC0_4,
            PA1_4,
            PC7_4,
            PA0_4,
            PB5_4,
            PB4_4,
            PB3_4,
            PB2_4,
            PB1_4,
            PB0_4,
            PD7_4,
            PD6_4,
            PD5_4,
            PB7_4,
            PB6_4,
            PA3_4,
            PA2_4,
            PA0_3,
            PA1_3,
            PC1_3,
            PD4_4,
            PD3_4,
            PC0_3,
            PC7_3,
            PB5_3,
            PB4_3,
            PB3_3,
            PB2_3,
            PB1_3,
            PB0_3,
            PD7_3,
            PD6_3,
            PD5_3,
            PB7_3,
            PB6_3,
            PA3_3
        }

        private List<byte> MCU_1 = new List<byte>();
        private List<byte> MCU_2 = new List<byte>();
        private List<byte> MCU_3 = new List<byte>();
        private List<byte> MCU_4 = new List<byte>();

    }
}
